### ISSUE TITLE
Allow Engine types other than MergeTree

### ISSUE THREAD

**Issue by RamlahAziz** [shaped-ai/target-clickhouse#33]
Options to add ENGINE types other than MergeTree would be great. 
When creating tables, if we could specify the engine type such as MergeTree, ReplacingMergeTree, ReplicatedReplacingMergeTree etc. that would be super helpful.

**Comment by BTheunissen** [comment]
Thanks for the issue and PR. I'll close this one as your PR has been merged and will keep active on this repository for future issues.
